Feature user can upvote a question
cdfuller/DonutOverflow pull request #20
Opened 2017-02-03 21:54 UTC by jwharrow

currently allows user to vote more than once.
currenrtly separate forms for upvote and downvote. could combine forms to single form and make it work with CSS.

2017-02-03 22:51 UTC, cdfuller requested changes
Vote validation needs work. Need to insure user can only vote once.

2017-02-03 22:51 UTC, cdfuller commented on app/controllers/votes_controller.rb
> +  erb :"questions/show"
Currently broken. This view also requires `@answers` to render. I believe redirecting to '/questions/:id' would be a better option here.

2017-02-03 22:51 UTC, cdfuller commented on joe_notes.md
> +joe_notes.md
This file isn't needed.

2017-02-03 22:52 UTC, cdfuller commented
Currently working on this.

2017-02-04 01:33 UTC, jwharrow commented on app/controllers/votes_controller.rb
> +  erb :"questions/show"
agree. made changes.

2017-02-04 22:04 UTC, closed without merging